### ISSUE TITLE
Fix Page Metadata

### ISSUE THREAD

**Issue by ryangchung** [CarletonComputerScienceSociety/students#13]
As seen in the image below, the metadata of the website is incomplete. Find "tbd" and "coming soon" in the codebase, and substitute it by the title and description of the pages.

![image](https://github.com/CarletonComputerScienceSociety/resources/assets/87027981/fc12f4c6-ab94-489c-81e5-29c5b34a8e25)

**Comment by sfahimanwar** [comment]
I want to take this issue if that's okay

**Comment by ryangchung** [comment]
> I want to take this issue if that's okay

Assigned! Let me know if you need any help :)
